#!/bin/bash

#i am not getting this git pull and push in git hub

echo "01-hello world"
echo "02-after several attempts i am not able to execuite the echo command"
echo "03-not i am feeling very happy that i was completed first stage"
echo "04-want to practice again make some changes and add to git again and push and pull"
echo "05-now just make another attempt and see how it will work the concept was understanded or not"
echo "06-ok well execuited now move to next step and learn more"