#!/bin/bash

#i am not getting this git pull and push in git hub

echo "hello world"
echo "after several attempts i am not able to execuite the echo command"
echo "not i am feeling very happy that i was completed first stage"
echo "want to practice again make some changes and add to git again and push and pull"
echo "now just make another attempt and see how it will work the concept was understanded or not"